// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   string    `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type Order struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	TokenID   int64 `json:"token_id"`
	// can be negative or positive
	Amount string `json:"amount"`
	Side   string `json:"side"`
	// can not be negative
	Price     string    `json:"price"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type Token struct {
	ID         int64     `json:"id"`
	ShortName  string    `json:"shortName"`
	Name       string    `json:"name"`
	DetailsEtc string    `json:"details_etc"`
	CreatedAt  time.Time `json:"created_at"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// it must be positive
	Amount    string    `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}
